services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pr1-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:80"
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./style.css:/var/www/html/style.css

  db:
    image: mysql:8.0
    container_name: pr1-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3606:3606
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

